spring:
  datasource:
    url: jdbc:mysql://cdb-354ib97z.gz.tencentcdb.com:10079/fires?requireSSL=false&connectionTimeout=2000&serverTimezone=Asia/Shanghai
    username: root
    password: db2sapdb@)@!
    hikari:
      maximumPoolSize: 3

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

