server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fires?requireSSL=false&connectionTimeout=2000&serverTimezone=Asia/Shanghai
    username: root
    password: db2sapdb
    hikari:
      maximumPoolSize: 3

mybatis:
  configuration:
    variables:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 下划线转驼峰
    map-underscore-to-camel-case: true
